name: Deploy to GitHub Pages

on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust and WASM
              uses: dtolnay/rust-toolchain@stable
              with:
                targets: wasm32-unknown-unknown
                toolchain: stable
                profile: minimal
            - name: Build WASM
              run: cargo build --target wasm32-unknown-unknown --release
            
            - name: Install cargo-binstall
              uses: cargo-bins/cargo-binstall@main
            - name: Install wasm-bindgen
              run: cargo binstall wasm-bindgen-cli -y
            - name: Build Site
              run: wasm-bindgen --no-typescript --target web --out-dir ./site --out-name "bevy-shader-test" ./target/wasm32-unknown-unknown/release/bevy-shader-test.wasm
            - name: Copy Assets to Site
              run: cp -r ./assets ./site/assets

            - name: Upload Site Artifact
              uses: actions/upload-artifact@v3
              with:
                name: bevy-shader-test
                path: site

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment: github-pages

        permissions:
            pages: write
            contents: write
            id-token: write

        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                name: bevy-shader-test
                path: .
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
