name: Deploy to GitHub Pages

on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        environment: build-site
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust and WASM
              uses: dtolnay/rust-toolchain@stable
              with:
                targets: wasm32-unknown-unknown
                toolchain: stable
            - name: Build WASM
              run: cargo build --target wasm32-unknown-unknown --release
            
            - name: Install cargo-binstall
              uses: cargo-bins/cargo-binstall@main
            - name: Install wasm-bindgen
              run: cargo binstall wasm-bindgen-cli --version 0.2.89 -y
            - name: Build Site
              run: wasm-bindgen --no-typescript --target web --out-dir ./site --out-name "bevy-shader-test" ./target/wasm32-unknown-unknown/release/bevy-shader-test.wasm
            - name: Copy Assets to Site
              run: cp -r ./assets ./site/assets

            - name: Upload Site Artifact
              uses: actions/upload-artifact@v3
              with:
                name: bevy-shader-test
                path: site

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment: build-site

        permissions:
            pages: write
            contents: write
            id-token: write
            actions: read
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v4.1.7
              with:
                name: bevy-shader-test
                path: site
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: site
